'use strict';

// Based on Pocketpair's Palworld Server Guide 1.0 configuration and PvP references.
// Settings Pocketpair does not define publicly are identified as advanced/internal instead of guessed at.
const DESCRIPTIONS = Object.freeze({
  Difficulty: 'Selects Palworld\'s base difficulty preset. The individual multipliers below can further customize the selected preset.',
  RandomizerType: 'Controls wild Pal spawn randomization: None keeps normal spawns, Region shuffles within regions, and All randomizes the whole world.',
  RandomizerSeed: 'Seed used to reproduce the same randomized Pal distribution. It matters only when Randomizer Type is Region or All.',
  bIsRandomizerPalLevelRandom: 'When randomization is active, fully randomizes wild Pal levels. When off, levels stay within each area\'s intended range.',
  DayTimeSpeedRate: 'Multiplier for how quickly daytime passes. Higher values shorten the day; lower values make daylight last longer.',
  NightTimeSpeedRate: 'Multiplier for how quickly nighttime passes. Higher values shorten the night; lower values make darkness last longer.',
  ExpRate: 'Multiplier for experience earned by players and Pals. For example, 2.0 awards twice the normal experience.',
  PalCaptureRate: 'Multiplier applied to Pal capture chance. Higher values make captures easier; lower values make them harder.',
  PalSpawnNumRate: 'Multiplier for the number of wild Pals that spawn. Higher values make the world busier and can substantially increase server load.',
  PalDamageRateAttack: 'Multiplier for damage dealt by Pals. Values above 1.0 make Pal attacks stronger.',
  PalDamageRateDefense: 'Multiplier for damage received by Pals. Values above 1.0 make Pals take more damage, not less.',
  PlayerDamageRateAttack: 'Multiplier for damage dealt by players. Values above 1.0 make player attacks stronger.',
  PlayerDamageRateDefense: 'Multiplier for damage received by players. Values above 1.0 make players take more damage, not less.',
  PlayerStomachDecreaceRate: 'Multiplier for player hunger depletion. Higher values drain hunger faster; lower values make food last longer.',
  PlayerStaminaDecreaceRate: 'Multiplier for player stamina consumption. Higher values drain stamina faster; lower values allow longer activity.',
  PlayerAutoHPRegeneRate: 'Multiplier for a player\'s natural health regeneration while awake. Higher values restore health faster.',
  PlayerAutoHpRegeneRateInSleep: 'Multiplier for player health regeneration while sleeping. Higher values restore sleeping players faster.',
  PalStomachDecreaceRate: 'Multiplier for Pal hunger depletion. Higher values make Pals need food more often.',
  PalStaminaDecreaceRate: 'Multiplier for Pal stamina consumption. Higher values make Pals tire more quickly.',
  PalAutoHPRegeneRate: 'Multiplier for a Pal\'s natural health regeneration while active. Higher values restore health faster.',
  PalAutoHpRegeneRateInSleep: 'Multiplier for Pal health regeneration while sleeping or stored in the Palbox. Higher values heal Pals faster.',
  BuildObjectHpRate: 'Multiplier for the maximum health of player-built structures. Higher values make buildings harder to destroy.',
  BuildObjectDamageRate: 'Multiplier for damage received by player-built structures. Higher values make buildings easier to destroy.',
  BuildObjectDeteriorationDamageRate: 'Multiplier for structure decay outside protected base areas. Higher values make unprotected buildings deteriorate faster.',
  CollectionDropRate: 'Multiplier for items gained from gatherable world objects such as trees, rocks, and resource nodes.',
  CollectionObjectHpRate: 'Multiplier for the health of gatherable world objects. Higher values require more hits before the object breaks.',
  CollectionObjectRespawnSpeedRate: 'Multiplier for gatherable-object respawn intervals. Higher values lengthen the interval and make resources return more slowly.',
  EnemyDropItemRate: 'Multiplier for the quantity of items dropped by defeated enemies. Higher values produce more loot.',
  DeathPenalty: 'Controls what is dropped on death: nothing, inventory items, items plus equipment, or items, equipment, and carried Pals.',
  bEnablePlayerToPlayerDamage: 'Allows players to damage other players. Pocketpair requires this together with PvP Mode and Defend Against Other Guilds for full PvP.',
  bEnableFriendlyFire: 'Allows attacks to damage friendly players or allied targets. Leave off for ordinary cooperative play.',
  bEnableInvaderEnemy: 'Enables hostile invasion or raid events against player bases.',
  bActiveUNKO: 'Advanced legacy option for generating Pal waste as dropped world items. Pocketpair does not currently document it; leave at the default unless testing.',
  bEnableAimAssistPad: 'Enables aim assistance for controller users. Pocketpair recommends considering this setting when balancing PvP.',
  bEnableAimAssistKeyboard: 'Enables aim assistance for keyboard and mouse input. Leave off for normal mouse aiming.',
  DropItemMaxNum: 'Maximum number of ordinary dropped-item entities kept in the world. Raising it can increase memory, save size, and synchronization load.',
  PhysicsActiveDropItemMaxNum: 'Maximum number of dropped items allowed to use active physics. Use -1 for Palworld\'s unlimited/default behavior; high limits cost performance.',
  DropItemMaxNum_UNKO: 'Advanced limit for Pal waste drops kept in the world. Pocketpair does not currently document this option; leave it at the default unless needed.',
  BaseCampMaxNum: 'Maximum total number of bases allowed across the entire server. More bases increase simulation and save-data load.',
  BaseCampWorkerMaxNum: 'Maximum number of working Pals at each base, up to 50. Higher limits increase base simulation and server load.',
  DropItemAliveMaxHours: 'Number of real-time hours dropped items remain before despawning. Longer retention increases world clutter and save size.',
  bAutoResetGuildNoOnlinePlayers: 'Deletes an abandoned guild\'s structures and base Pals after no members log in for the configured offline period.',
  AutoResetGuildTimeNoOnlinePlayers: 'Hours a guild may remain completely offline before automatic guild cleanup runs. Ignored when automatic guild cleanup is off.',
  GuildPlayerMaxNum: 'Maximum number of players allowed in one guild. Smaller guilds can improve PvP balance and limit shared-base growth.',
  BaseCampMaxNumInGuild: 'Maximum bases one guild may own, up to 10. More bases per guild increase server processing load.',
  PalEggDefaultHatchingTime: 'Hours required to incubate a Huge Egg; other egg sizes scale from this value. Set lower for faster breeding.',
  WorkSpeedRate: 'Multiplier for player and Pal work speed. Higher values shorten crafting and production time.',
  AutoSaveSpan: 'Seconds between automatic world saves. Shorter intervals reduce potential progress loss but create more frequent disk activity.',
  bIsMultiplay: 'Legacy/internal multiplayer flag retained in Palworld\'s default file. Dedicated-server multiplayer works independently; leave this at its default.',
  bIsPvP: 'Enables Palworld\'s trial PvP rule set. Full PvP also requires Player-to-Player Damage and Defend Against Other Guilds.',
  bHardcore: 'Enables Hardcore mode, where a dead character cannot normally respawn.',
  bPalLost: 'Permanently removes carried Pals when a player dies. This is separate from the normal Death Penalty selection.',
  bCharacterRecreateInHardcore: 'Allows a player who dies in Hardcore mode to create a replacement character instead of being permanently locked out.',
  bCanPickupOtherGuildDeathPenaltyDrop: 'Allows players outside the victim\'s guild to collect items and Pals dropped by that player on death.',
  bEnableNonLoginPenalty: 'Advanced offline-penalty toggle affecting inactive players or guilds. Pocketpair does not currently define its exact scope; leave at the default.',
  bEnableFastTravel: 'Enables fast travel. Turn it off to require all travel through the world.',
  bEnableFastTravelOnlyBaseCamp: 'Restricts fast travel to routes between bases. It has an effect only while Fast Travel is enabled.',
  bIsStartLocationSelectByMap: 'Lets new or recreated characters choose a starting location from the map instead of using the default spawn.',
  bExistPlayerAfterLogout: 'Leaves logged-out players sleeping at their last location, preventing logout from being used to escape PvP combat.',
  bEnableDefenseOtherGuildPlayer: 'Makes base Pals defend against hostile players from other guilds. Pocketpair requires this for the full PvP rule set.',
  bInvisibleOtherGuildBaseCampAreaFX: 'Hides other guilds\' base-area boundaries when enabled. Turn it off to make those boundaries visible.',
  bBuildAreaLimit: 'Prevents construction at protected locations such as spawn points and fast-travel sites. Recommended for public or PvP servers.',
  ItemWeightRate: 'Multiplier for item weight. Higher values make inventories reach their carrying limit sooner.',
  CoopPlayerMaxNum: 'Player limit for hosted co-op sessions. Dedicated servers use Dedicated Server Player Limit instead, so this normally has no effect here.',
  ServerPlayerMaxNum: 'Maximum simultaneous players on this dedicated server. Palworld supports up to 32; larger populations require more host resources.',
  ServerName: 'Name shown to players in connection screens and the Community Servers list.',
  ServerDescription: 'Message players see when joining. PalSphere appends its fixed hosting signature after your custom text.',
  AdminPassword: 'Secret used to gain administrator privileges and by PalSphere for local save and shutdown controls. Do not share it with players.',
  ServerPassword: 'Password players must enter to join. Use one whenever the server is reachable from the internet or publicly listed.',
  bAllowClientMod: 'Allows clients running supported mods to join. Mods can cause incompatibility, crashes, or save corruption, so enable deliberately.',
  PublicPort: 'UDP game port PalSphere passes to Palworld and displays to players. Forward this same UDP port in the router; do not forward the REST port.',
  PublicIP: 'Optional manual external IPv4 address for Community Server registration. Leave blank for automatic detection unless listing fails.',
  RCONEnabled: 'Enables remote console administration. Leave off unless an RCON client is required, and never expose it without strong access controls.',
  RCONPort: 'TCP port used by RCON when it is enabled. It has no effect while RCON is off.',
  Region: 'Optional region tag used for server discovery and filtering. Leave blank to let Palworld use its normal behavior.',
  bUseAuth: 'Requires platform authentication for joining. Leave enabled for normal internet and Community Server operation.',
  BanListURL: 'URL of the remote ban list Palworld downloads. Keep Pocketpair\'s official URL unless you operate a compatible trusted list.',
  RESTAPIEnabled: 'Enables Palworld\'s local management API. PalSphere needs it for player status, Save Now, and graceful shutdown.',
  RESTAPIPort: 'Local TCP port for Palworld\'s management API. PalSphere connects locally; do not port-forward or expose this port to the internet.',
  bShowPlayerList: 'Shows the connected-player list from the in-game ESC menu.',
  ChatPostLimitPerMinute: 'Maximum chat messages one player may post per minute. Lower values reduce spam but can restrict normal conversation.',
  CrossplayPlatforms: 'Platforms permitted to join this server. Removing a platform blocks players using that ecosystem.',
  bIsUseBackupSaveData: 'Enables Palworld\'s built-in rolling world backups. It adds disk writes but provides short-, hourly-, and daily recovery points.',
  LogFormatType: 'Chooses human-readable Text logs or structured Json logs. Text is easier to read; Json is easier for log-processing tools.',
  bIsShowJoinLeftMessage: 'Shows an in-game notification when a player joins or leaves the dedicated server.',
  SupplyDropSpan: 'Minutes between meteorite or supply-drop events. Lower values make these events occur more frequently.',
  EnablePredatorBossPal: 'Enables Predator Pal encounters and bosses. Turn off to remove this world feature.',
  MaxBuildingLimitNum: 'Maximum structures each player may build; 0 means unlimited. Lower limits reduce save growth and server strain.',
  ServerReplicatePawnCullDistance: 'Maximum distance at which Pals synchronize to players, in centimeters (5,000–15,000). Higher values increase network and CPU load.',
  bAllowGlobalPalboxExport: 'Allows players to save Pals from this world into the Global Palbox for use elsewhere.',
  bAllowGlobalPalboxImport: 'Allows players to bring Pals from the Global Palbox into this world. Disable for a closed-progression economy.',
  EquipmentDurabilityDamageRate: 'Multiplier for durability lost by weapons, armor, and tools. Higher values make equipment wear out faster.',
  ItemContainerForceMarkDirtyInterval: 'Seconds between forced container re-synchronizations while its UI is open. Lower values update more often but increase replication work.',
  PlayerDataPalStorageUpdateCheckTickInterval: 'Advanced interval for checking player Pal-storage updates. Pocketpair does not document its unit or tuning; leave at the default.',
  ItemCorruptionMultiplier: 'Multiplier for food spoilage and other item corruption. Higher values make perishable items expire faster.',
  MonsterFarmActionSpeedRate: 'Multiplier for item production by grazing Pals at a Ranch. Higher values produce ranch items faster.',
  DenyTechnologyList: 'Technology IDs players are forbidden to unlock or use. Enter exact Pocketpair technology IDs; useful for PvP balance rules.',
  GuildRejoinCooldownMinutes: 'Minutes a player must wait before rejoining a guild after leaving. Use a cooldown to prevent rapid guild switching in PvP.',
  AutoTransferMasterCheckIntervalSeconds: 'Advanced interval, in seconds, between checks for automatically transferring leadership from an inactive guild master.',
  AutoTransferMasterThresholdDays: 'Days a guild master may remain inactive before Palworld can transfer leadership to another member.',
  MaxGuildsPerFrame: 'Advanced batch limit for guild maintenance processed in one server frame. Higher values finish checks sooner but may cause frame-time spikes.',
  BlockRespawnTime: 'Base delay, in seconds, before a dead player may respawn.',
  RespawnPenaltyDurationThreshold: 'Seconds a player must survive without dying before the escalating respawn penalty resets to the base delay.',
  RespawnPenaltyTimeScale: 'Multiplier applied to the respawn delay after repeated deaths within the threshold. For example, 2.0 doubles the delay.',
  bDisplayPvPItemNumOnWorldMap_BaseCamp: 'Shows each base\'s quantity of the configured PvP reward item on the world map. Used only with PvP reward rules.',
  bDisplayPvPItemNumOnWorldMap_Player: 'Shows player locations and carried PvP reward-item quantities on the world map. Used only with PvP reward rules.',
  AdditionalDropItemWhenPlayerKillingInPvPMode: 'Item ID awarded or dropped when one player kills another in PvP. Used only when Additional PvP Kill Item is enabled.',
  AdditionalDropItemNumWhenPlayerKillingInPvPMode: 'Quantity of the configured PvP reward item dropped for a player kill. Used only when Additional PvP Kill Item is enabled.',
  bAdditionalDropItemWhenPlayerKillingInPvPMode: 'Enables a special item drop when a player is killed in PvP, allowing custom reward or victory-condition rules.',
  bEnableVoiceChat: 'Enables Palworld\'s in-game proximity voice chat for connected players.',
  VoiceChatMaxVolumeDistance: 'Distance within which proximity voice remains at full volume. Beyond this point, volume begins to fade.',
  VoiceChatZeroVolumeDistance: 'Distance at which proximity voice becomes completely inaudible. Keep it greater than Full-Volume Distance.',
  bAllowEnhanceStat_Health: 'Allows players to spend stat points on maximum Health. Pocketpair recommends disabling this for stricter PvP balance.',
  bAllowEnhanceStat_Attack: 'Allows players to spend stat points on Attack. Pocketpair recommends disabling this for stricter PvP balance.',
  bAllowEnhanceStat_Stamina: 'Allows players to spend stat points on Stamina.',
  bAllowEnhanceStat_Weight: 'Allows players to spend stat points on Carry Weight.',
  bAllowEnhanceStat_WorkSpeed: 'Allows players to spend stat points on Work Speed.',
  bEnableBuildingPlayerUIdDisplay: 'Displays the creating player\'s ID on structures, making ownership and moderation investigations easier.',
  BuildingNameDisplayCacheTTLSeconds: 'Advanced cache lifetime, in seconds, for building-name display data. Leave at default unless troubleshooting stale labels or cache load.',
});

const LABEL_OVERRIDES = Object.freeze({
  Difficulty: 'Difficulty preset',
  bActiveUNKO: 'Generate Pal waste drops',
  DropItemMaxNum_UNKO: 'Pal waste drop limit',
  bIsMultiplay: 'Legacy multiplayer flag',
  bIsPvP: 'PvP mode',
  bEnablePlayerToPlayerDamage: 'Player-to-player damage',
  bEnableDefenseOtherGuildPlayer: 'Defend against other guilds',
  CoopPlayerMaxNum: 'Co-op player limit',
  ServerPlayerMaxNum: 'Dedicated server player limit',
  ServerDescription: 'Join message',
  PublicPort: 'Game/public UDP port',
  PublicIP: 'Manual public IP',
  bUseAuth: 'Require platform authentication',
  BanListURL: 'Remote ban-list URL',
  bIsShowJoinLeftMessage: 'Show join and leave messages',
  bIsUseBackupSaveData: 'Built-in rolling backups',
  LogFormatType: 'Log format',
  bEnableBuildingPlayerUIdDisplay: 'Show builder player ID',
});

module.exports = { DESCRIPTIONS, LABEL_OVERRIDES };
